version: "3.9"

services:
  
  api:
    image: chronark/queue-api
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      REDIS_ADDR: redis:6379

  redis:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    depends_on:
      - redis
  
  questdb:
    image: questdb/questdb
    ports:
      - 9000:9000